#!/bin/ash
# fw-mirror?volName=<volName>&size=<size>

echo "QUERY_STRING ${QUERY_STRING}" >/tmp/webroot-debug 
date >>/tmp/webroot-debug
failure=
# Ensure there's nothing more than name=val in arguments
echo ${QUERY_STRING} | grep -q -E '^([a-zA-Z_][a-zA-Z_0-9]*=[^ &]+&)*[a-zA-Z_][a-zA-Z_0-9]*=[^ ]+$' || \
  failure='Arguments not simply name=value'

# Get actual destination from query
if [ -z "${failure}" ]; then
 eval "${QUERY_STRING//&/; }"
 # validate size=
 echo "${size}" | grep -q '^[0-9][0-9]*$' || \
   failure="Missing or ill-formed size \"${size}\""
fi
if [ -z "${failure}" ]; then
 # validate size name existss in mtd
 hexsize=`dc ${size} 16 o p`
 mtdn=`sed -n -e "s;^\([^:]*\): 0*${hexsize} [0-9a-f]* \"${volName}\""'$;\1;p' /proc/mtd`
 [ -z "${mtdn}" ] && failure="Cannot find ${size} [0x${hexsize}] volume \"${volName}\" in /proc/mtd"
fi
if [ -z "${failure}" ]; then
 # find volume in manifest
 manifest=`grep -l "volName=${volName}" /webroot/bank*/*.txt | head -1`
 [ -z "${manifest}" ] && failure="Cannot find manifest for \"${volName}\""
fi
if [ -z "${failure}" ]; then
 # find certificate in manifest
 cert=`sed -n -e "s;^[^\t]*\t[^\t]*volName=${volName}[^\t]*\t[^\t]*\t\([^\t]*\).*;\1;p" ${manifest} | head -1`
 [ -z "${cert}" ] && failure="Cannot find certificate for \"${volName}\""
fi
if [ -z "${failure}" ]; then
 # check for reasonable date
 udate=`date +%s`
 fdate=`date +%s -r ${manifest}`
 echo "udate ${udate} <? ${manifest} ${fdate}" >>/tmp/webroot-debug
 if [ ${udate} -lt ${fdate} ]; then
  date -s @$fdate
  pdate=`date +'%F %T'`
  echo ${pdate} >>/tmp/webroot-debug
  logger -t fw-mirror -p info "date set to ${pdate} from ${manifest}"
 fi
 # validate certificate part of cert
 echo -----BEGIN CERTIFICATE-----@`echo ${cert#*@} | sed -e 's;.................................................................;&@;g'`@-----END CERTIFICATE----- | \
   tr @ \\n >/tmp/fw$$-certificate
 cat /tmp/fw$$-certificate | openssl verify -CApath /nvdata/certs/fwca >/tmp/fw$$-verify
 status=$?
 if [ $status -ne 0 -o "`cat /tmp/fw$$-verify`" != "stdin: OK" ]; then
  failure="Volume \"${volName}\" certificate failed verify \"`cat /tmp/fw$$-verify`\", status $status"
 fi
fi
if [ -z "${failure}" ]; then
 # extract public key from certificate
 openssl x509 -in /tmp/fw$$-certificate -pubkey -noout >/tmp/fw$$-pubkey
 # extract signature from manifest cert
 echo ${cert%*@} | base64 -d >/tmp/fw$$-signature
 openssl dgst -sha1 -verify /tmp/fw$$-pubkey -signature /tmp/fw$$-signature /dev/${mtdn} > /tmp/fw$$-verify
 status=$?
 if [ $status -ne 0 -o "`cat /tmp/fw$$-verify`" != "Verified OK" ]; then
  result="Volume \"${volName}\" signature failed verify \"`cat /tmp/fw$$-verify`\", status $status"
 fi
fi
if [ -z "${failure}" ]; then
 # Serve the firmware contents
 echo "Content-Type: application/octet-stream"
 echo "Content-Length: ${size}"
 echo
 nice dd if=/dev/${mtdn} ibs=1 count=${size}
else
 # Report the failure
 echo "Status: 500"
 echo "Content-Type: text/html"
 echo
 echo "<html><body><h1>Error 500: Cannot Serve Requested Firmware</h1><p>${failure}</p></body></html>"
 echo "${failure}" >>/tmp/webroot-debug
fi
