# ALSA drivers configuration file
#
# For more information on configuring ALSA drivers visit the web site
# http://alsa.opensrc.org/index.php/.asoundrc

#
# Playback devices
#

# Default playback device
pcm.!default {
    type plug
    slave {
        pcm "lineout"
    }
}

pcm.speakerphone {
    type hw
    card 0
    device 0
}

pcm.handset {
    type hw
    card 0
    device 1
}

pcm.headset {
    type hw
    card 0
    device 2
}

pcm.lineout {
    type hw
    card 0
    device 3
}

#
# Mixer devices
#

# Default mixer device
ctl.!default {
    type hw
    card 0
}

