[SUID]
httpd       = sx- root.adm      # for update-
mdev        = sx- root.adm      # for update-
reboot      = sx- root.adm      # for update-
su          = sx- root.adm      # e.g. no takeover by phone application
netcfgu     = sx- root.phone    # for p*_phone
suphone     = sx- root.phone    # for p*_phone
