# altbank
/usr/bin/update-status
# callperfmonitor, clicmds, traceroutediagsubviewclr
/usr/sbin/traceroute -I icmp -n -w [1-9] -q [1-9]( -m [0-9]+){0,1} [0-9a-zA-Z._-]+
# cliclr
chgrp adm /tmp/cli_interface_socket[^&();<>|]*
# configclr
/usr/bin/ftclean --reboot --keep-logs( --for-test){0,1}
# dhcpclr
/usr/bin/killall -q udhcpc
/bin/rm -f /var/run/udhcpc.socket
(nice -n [0-9]+ ){0,1}/usr/sbin/udhcpc -f -i (eth|rast)[0-9.]+ -s /usr/sbin/dhcpcom( -r [0-9.]+| -H [0-9A-Za-z_-]+| -x [0-9]+| -e [0-9.A-Za-z_-]+)*
/bin/kill -SIGUSR2 [0-9]+
# dot1xclr
/usr/bin/killall -q wpa_supplicant
/bin/rm -f /var/run/wpa_supplicant/(eth|rast)[0-9.]+
/usr/bin/cmp -s /tmp/wpa_supplicant.conf /etc/wpa_supplicant.conf
/bin/cp -f /tmp/wpa_supplicant.conf /etc/wpa_supplicant.conf
(nice -n [0-9]+ ){0,1}/usr/sbin/wpa_supplicant -i (eth|rast)[0-9.]+ -c /etc/wpa_supplicant.conf
(nice -n [0-9]+ ){0,1}/usr/sbin/wpa_cli status verbose
# eptecan
cmp -s /tmp/ecregs /etc/spkrphone_ecregs
cp -f /tmp/ecregs /etc/spkrphone_ecregs
# hotfixclr
touch /nvdata/hotfixes/[^&();<>|]*
hotfix --(un|)install[^&();<>|]*
# ipwatch
/usr/bin/killall -q ipwatchd
/bin/rm -f /var/run/ipwatchd.socket
/usr/bin/cmp -s /tmp/ipwatchd.conf /etc/ipwatchd.conf
/bin/cp -f /tmp/ipwatchd.conf /etc/ipwatchd.conf
(nice -n [0-9]+ ){0,1}/usr/sbin/ipwatchd -f -c /etc/ipwatchd.conf
# lldpclr
/usr/bin/killall -q lldpd
/bin/rm -f /var/run/lldpd.socket
/bin/mkdir -p /var/run/lldpd
(nice -n [0-9]+ ){0,1}/usr/sbin/lldpd -M 3 -d -S [ 0-9.:A-Za-z]*
/usr/sbin/lldpctl( -f xml| (-[pP] [0-9:]+|-D .*))( (usb|eth|rast)[0-9.]+){0,4}
# logbundle
chmod a\+r /core
rm -f /core
rm -f /tmp/debug.log
/usr/sbin/logrotate /etc/logrotate.conf
# logrotatecfgclr
/usr/bin/cmp -s /tmp/[.a-z]+ /etc/logrotate.d/[.a-z]+
/bin/cp -f /tmp/[.a-z]+ /etc/logrotate\.d/[.a-z]+
/bin/chmod 644 /etc/logrotate.d/[.a-z]+
# netcfgclr
(nice -n [0-9]+ ){0,1}/bin/netcfg( -c [0-9]+| -d [0-9]+| -i| -p [0-9]+| -r [0-9]+:[0-9]+| -s [0-9]+| -u| -v [0-9]+)+
/usr/bin/arping -q -U -c 1 -I (eth|rast)[0-9.]+ [0-9.]+
/sbin/ifconfig (eth|rast)[0-9.]+( [0-9.]+( netmask [0-9.]+){0,1}){0,1} up
/bin/sh -c /bin/echo [0-9]+ > /proc/sys/net/ipv4/tcp_retries2
/sbin/route (add|del) (default|-host [0-9.]+) (dev (eth|rast)[0-9.]+|gw [0-9.]+)
/sbin/route add -net 0.0.0.0 netmask 0.0.0.0 eth0
/sbin/iptables -[AD] INPUT -j DROP -p (tcp|udp) --dport [0-9]+
# bbox::rpcclient
/usr/bin/update-stage-do --idle --bb [0-9.]+ [0-9.]+[0-9:]*
# notifyclr
/usr/bin/update-stage [0-9.]+ [0-9A-Za-z.-]+[0-9:]*
/usr/bin/update-do --idle| [0-9.]+
/usr/bin/update-mirror
# powermanager
usbif (up|down)
# pphoneclr
/sbin/reboot
/bin/cp -f /tmp/etc-passwd /etc/passwd
# rastvpn
/usr/bin/killall -q rastd
/usr/bin/cmp -s /tmp/rastd.conf /etc/rastd.conf
/bin/cp -f /tmp/rastd.conf /etc/rastd.conf
/usr/sbin/rastd /etc/rastd.conf
/usr/sbin/rastd /etc/rastd.conf [0-9]+ [0-9a-f]+
# securitysshclr
/bin/rm -f /tmp/authorized_keys
/bin/cat /home/admin/\.ssh/authorized_keys
/bin/chown phone:phone /tmp/authorized_keys
/bin/mkdir -p /home/admin/\.ssh
/bin/cp -f /tmp/authorized_keys.new /home/admin/\.ssh/authorized_keys
/bin/chown -R admin:adm /home/admin/\.ssh
/bin/chmod -R go-rwx /home/admin/\.ssh
# sntpclr
/usr/bin/killall -q ntpclient
(nice -n [0-9]+ ){0,1}/usr/sbin/ntpclient -i [0-9]+ -l -c 0 -s -t -h [0-9a-zA-Z._-]+
# syslogclr
/etc/init.d/log reload (none|[0-9a-zA-Z._-]+:[0-9]+;(tcp|udp))
# vpnclr
/bin/rm -f /var/run/vpn-socket
# skyconfigclr
nslookup [0-9.]+
